PROMPTS = {
    "intentdetection": (
        "You are an expert travel coordinator. Classify the user's input message into one of these intents:\n"
        "SUPPORTED_INTENTS = ['travelquestion', 'destinationrecommendation', 'plantrip', 'modifytrip', 'weatherquery', 'visaquery', 'budgetquery', 'hotelsearch', 'flightsearch', 'itinerarygeneration', 'nontravel']\n\n"
        "Trip context:\n"
        "{current_state}\n\n"
        "User message: \"{message}\"\n\n"
        "Output ONLY a single valid JSON object containing:\n"
        "{{\n"
        "  \"intent\": \"<intent_name>\",\n"
        "  \"confidence\": <float_between_0_and_1>\n"
        "}}\n"
        "Ensure no markdown wrapping, additional text, or explanation."
    ),
    "entityextraction": (
        "You are a travel data extractor. Extract travel entity values from the user query. Output ONLY valid JSON matching this schema:\n"
        "{{\n"
        "  \"destination\": \"string or null\",\n"
        "  \"country\": \"string or null\",\n"
        "  \"startdate\": \"YYYY-MM-DD or null\",\n"
        "  \"enddate\": \"YYYY-MM-DD or null\",\n"
        "  \"budget\": number or null,\n"
        "  \"currency\": \"string or null\",\n"
        "  \"travelercount\": number or null,\n"
        "  \"travelertype\": \"solo | couple | family | group or null\",\n"
        "  \"interests\": [\"string\"]\n"
        "}}\n\n"
        "User query: \"{message}\"\n"
        "Do NOT write any text other than the JSON object."
    ),
    "travelassistantresponse": (
        "You are an expert travel assistant. Answer the user's travel-related query clearly, concisely, and based only on verified facts.\n"
        "If the query is about the user's current trip or itinerary, refer to the provided Trip Details / Itinerary below. Do not make up or hallucinate details that are not in the itinerary.\n\n"
        "Trip Details / Itinerary:\n"
        "{itinerary_context}\n\n"
        "Chat History:\n"
        "{chat_history}\n\n"
        "User query: \"{message}\"\n\n"
        "Response:"
    ),
    "nontravelredirect": (
        "I'm specialized in travel planning and advice. I'd be happy to help you with destinations, itineraries, visa info, or travel tips!"
    ),
    "followupquestion": (
        "You are a friendly travel assistant helping the user plan their trip. You have gathered some details, but still need the following missing fields:\n"
        "Missing fields: {missing_fields}\n"
        "Current trip details: {current_state}\n\n"
        "Write a natural, polite, and friendly follow-up question to ask the user for the first missing detail (do not ask for multiple things at once)."
    ),
    "itinerarygeneration": (
        "You are an expert travel planner. Create a detailed travel itinerary for {destination}, {country} from {startdate} to {enddate} for {travelercount} travelers ({travelertype}).\n"
        "Interests: {interests}\n"
        "Budget limit: {budget} {currency}\n\n"
        "Output ONLY a single valid JSON object with the following structure:\n"
        "{{\n"
        "  \"destination\": \"{destination}\",\n"
        "  \"country\": \"{country}\",\n"
        "  \"startdate\": \"{startdate}\",\n"
        "  \"enddate\": \"{enddate}\",\n"
        "  \"travelercount\": {travelercount},\n"
        "  \"travelertype\": \"{travelertype}\",\n"
        "  \"interests\": {interests},\n"
        "  \"days\": [\n"
        "    {{\n"
        "      \"day\": 1,\n"
        "      \"date\": \"YYYY-MM-DD\",\n"
        "      \"theme\": \"Day Theme\",\n"
        "      \"activities\": [\n"
        "        {{\n"
        "          \"name\": \"Activity Name\",\n"
        "          \"category\": \"attraction | restaurant | hotel | transport\",\n"
        "          \"description\": \"Description of the activity\",\n"
        "          \"coordinates\": {{ \"lat\": 0.0, \"lng\": 0.0 }},\n"
        "          \"estimateddurationminutes\": 90,\n"
        "          \"estimatedcost\": 20.00,\n"
        "          \"currency\": \"{currency}\",\n"
        "          \"openinghours\": \"hours or null\",\n"
        "          \"bookingnotes\": \"notes or null\"\n"
        "        }}\n"
        "      ]\n"
        "    }}\n"
        "  ]\n"
        "}}\n"
        "Provide realistic, concise names. Do not include markdown wrapping or extra comments."
    ),
    "chateditparse": (
        "You are an itinerary edit assistant. Parse the user's edit request on their current travel itinerary.\n"
        "User request: \"{message}\"\n\n"
        "Output ONLY valid JSON matching this schema:\n"
        "{{\n"
        "  \"operation\": \"replaceactivity | addactivity | removeactivity | moveactivity\",\n"
        "  \"day\": number,\n"
        "  \"timeslot\": \"morning | afternoon | evening | lunch\",\n"
        "  \"target\": \"string or null\",\n"
        "  \"position\": number or null\n"
        "}}\n"
        "Ensure no explanation or formatting text is returned."
    ),
    "budgetanalysis": (
        "Analyze the daily budget of {daily_budget} {currency} for a trip of {trip_duration_days} days to {destination}.\n"
        "Identify if this budget is tight or comfortable and list warnings if appropriate. Output ONLY valid JSON containing:\n"
        "{{\n"
        "  \"warnings\": [\"warning text string\"]\n"
        "}}"
    )
}
